[package]
name = "alrisnet-scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
regex = { version = "1.5" }
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.208", features = ["derive"] }
sqlx = { version = "0.8.1", features = ["runtime-tokio", "tls-rustls", "mysql"] }
tokio = { version = "1.39.3", features = ["full"] }
html-escape = { version = "0.2" }